# exemplo deu um netlify.toml
[build]
  base = "."
  command = "npm run dev"
  functions = "netlify/functions"
  publish = "./"

# Redirecionamento de todas as rotas para /index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200